name: macos-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
      
    - name: configure
      run: cmake -G "Unix Makefiles" -S . -B ./build
      
    - name: make
      run: cd build && make
