name: linux-verify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: update apt
      run: sudo apt-get update

    - name: package-install
      run: sudo apt-get install libx11-dev xorg-dev xorg openbox freeglut3-dev libudev-dev libopenal-dev libvorbis-dev libflac-dev
      
    - name: configure
      run: cmake -G "Unix Makefiles" -S . -B ./build
      
    - name: make
      run: cd build && make

    - name: start X server
      run: sudo X
      
    - name: configure X server
      run: export DISPLAY=:0 firefox
      
    - name: test
      run: build/tests/BLIB.t 
