name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake -G "Unix Makefiles" -S . -B ./build
    - name: make
      run: cd build  && make
    - name: unit test
      run: cd build/tests && ./BLIB.t
